### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by simonfunk** [white-frame/view#1]
Hi there

First, thanks for it, it's exactly what i need now :)

But i get a "Class not found" error when i try to use it \WhiteFrame\View::add('layout', 'sidebar-menu', 'my_module::layout.menu');

Any advice?

**Comment by IfnotFr** [comment]
Woops I think i missed to mention that you need to register the service provider of the package. Did you add the service provider `WhiteFrame\View\ViewServiceProvider` into your config ?

**Comment by simonfunk** [comment]
Yeah that was it :) thanks.
